### ISSUE TITLE
ADSR Envelope

### ISSUE THREAD

**Issue by jayanderson** [SamiPerttu/fundsp#12]
How would one implement an [ADSR](https://en.wikipedia.org/wiki/Envelope_(music)#ADSR) envelope with fundsp. I was going through [this tutorial](https://vaporsoft.net/creating-an-audio-plugin-with-rust-3/) which implemented a simple instrument which responded to note-on and -off events. It uses a simple envelope mostly to make sure the note ends. It isn't able to sustain.

I'm thinking it could be implemented with two envelopes multiplied together:

envelope = envelope_on * envelope_off.

The 'on' envelope takes care of going through the attack, decay, and settling on the sustain value and the 'off' envelope goes from 1.0 to 0.0 over the release period.

A note on event would look like:
- signal the 'on' envelope to begin (start at 0.0).
- signal the 'off' envelope to go directly to 1.0.

A note off event would look like:
- signal the 'off' envelope to begin (start at 1.0).

Example code:
```
    let offset_on = || tag(Tag::NoteOn as i64, 0.0);
    let env_on = || offset_on() >> envelope2(|t, offset| {
      let attack = 0.2;
      let decay = 0.2;
      let sustain = 0.5;

      let position = t - offset;
      if position < attack {
        position / attack
      } else if position < decay + attack{
        let decay_position = (position - attack) / decay;
        (1.0 - decay_position) * (1.0 - sustain) + sustain
      } else {
        sustain
      }
    });

    let offset_off = || tag(Tag::NoteOff as i64, 0.0);
    let env_off = || offset_off() >> envelope2(|t, offset| {
      // Somewhat hacky: using 0.0 as a sentinel value indicating that the 'off'
      // envelope should be disabled when a note is playing.
      if offset <= 0.0 {
        return 1.0;
      }

      let release = 0.2;
      let position = t - offset;
      if position < release {
        1.0 - position / release
      } else {
        0.0
      }
    });

    let env = env_on() * env_off();
```

Some questions:
- Is there a simpler way to implement this?
- Is signaling with the time a good way to signal note-on/off events?
- Would an envelope like this be worth including in fundsp itself?

**Comment by SamiPerttu** [comment]
Hi! Lovely bit of code you have there.

I think what you have is fairly simple. Signaling with time, that's a nice idea.

Your ADSR envelope would make a fine addition to FunDSP! You can make a PR if you like or I can look into it.

**Comment by jayanderson** [comment]
You'd most definitely be able to make the change more quickly than me (inexperience with rust and the project). That said I plan on playing with this a bit more. I'd like to figure out how to change the `attack`, `decay`, `sustain`, and `release` parameters at runtime. I tried some things and wasn't able to make it work. Do you have any suggestions on that?

**Comment by SamiPerttu** [comment]
Make them parameters; but then there aren't enough inputs in `lfo`. I have on the to-do list an LFO with arbitrary number of parameters. Another possibility is using `Arc` values shared with the closure.
