### ISSUE TITLE
Tags on crates.io

### ISSUE THREAD

**Issue by gjf2a** [SamiPerttu/fundsp#15]
This is a really fantastic crate and I have enjoyed using it thus far. 

It was pure luck that I found it. I searched `crates.io` on `input` looking for a console-keyboard input crate (ultimately settling on the excellent  `read_input` crate) and `fundsp` was the fifth on the list of results.

I had been looking in vain for a satisfactory synthesizer crate. This one has met my needs very well thus far!

I suggest adding the following keywords to help more people find it:

`#synthesizer` `#synth` `#music` `#sound` `#wave`

**Comment by SamiPerttu** [comment]
I added those keywords, thanks for the tip!
