### ISSUE TITLE
Load wave from bytes

### ISSUE THREAD

**Issue by majorcob** [SamiPerttu/fundsp#33]
Could functions be added to load a `Wave32`/`Wave64` from a slice of bytes? In my application I'd be receiving ogg data from an external source (no filesystem). 

From what I can tell Symphonia is able to create a `MediaSource` from a `Cursor`, so hopefully most of the implementation can be shared with the existing `load`/`load_track` functions.

**Comment by SamiPerttu** [comment]
Sure thing! I'll update this issue when it's ready.

**Comment by SamiPerttu** [comment]
It's ready now! I ended up with a static lifetime for the slice, let me know if that's a problem.

**Comment by majorcob** [comment]
Fantastic, thank you for the quick turnaround!
