### ISSUE TITLE
using global allocator in a no_std environment

### ISSUE THREAD

**Issue by nwesem** [SamiPerttu/fundsp#49]
hi i'm using fundsp in a `no_std` enviroment (daisy seed stm32h7) and have issues getting a graph running, I added a global allocator. I decided to use `talc`, allocator init shown below.

```rust
use talc::*;

static mut ARENA: [u8; 32000] = [0; 32000];

#[global_allocator]
static ALLOCATOR: Talck<spin::Mutex<()>, ClaimOnOom> = Talc::new(unsafe {
    // if we're in a hosted environment, the Rust runtime may allocate before
    // main() is called, so we need to initialize the arena automatically
    ClaimOnOom::new(Span::from_const_array(core::ptr::addr_of!(ARENA)))
})
.lock();
```

I can get a stacked lowpass_hz working like this (this was taken from my implementation doing this for every audio block in an interrupt)

```rust
for frame in audio_buffer {
    let input = An(AudioInput::new(*frame));

    let lp_filter = lowpass_hz(lp_freq, lp_q) | lowpass_hz(lp_freq, lp_q);
    let mut graph = input >> lp_filter;
    graph.set_sample_rate(SAMPLE_RATE as f64);

    *frame = graph.get_stereo().into();
}
```

but i have issues initializing a simple reverb (as taken from example folder)

```rust
let reverb = reverb2_stereo(20.0, 3.0, 1.0, 1.0, highshelf_hz(1000.0, 1.0, db_amp(-1.0)));
```

any ideas what my issues is? would appreciate the help

**Comment by SamiPerttu** [comment]
Hi! The basic issue is, you need to create the components outside the loop and then inside the loop you should just call `get_stereo` or whatever to get the samples. The components contain state that needs to be maintained between interrupts. So you need to find somewhere to store the graphs outside of the interrupts.

The `reverb2_stereo` opcode allocates a lot of memory for its buffers, hundreds of kB, so you need to take that into account.

**Comment by nwesem** [comment]
thx a lot for the hint @SamiPerttu , I will give it a try and come back to this thread

**Comment by nwesem** [comment]
I couldn't create the static variables of a e.g. reverb because of type inferencing, maybe because of this problem below, leaving a screenshot here taken from [RustNL meetups 2024](https://github.com/rustnl/meetups/blob/main/20240507-delft/slides/Async%20Rust%20in%20embedded%20systems%20with%20Embassy%20-%20Dario%20Nieuwenhuis.pdf) to try this when I get the time to do that

or youtube link https://www.youtube.com/watch?v=H7NtzyP9q8E

<img width="809" alt="Screenshot 2024-09-03 at 09 38 08" src="https://github.com/user-attachments/assets/32035314-a0b6-4a00-a840-37ac201fa543">

**Comment by SamiPerttu** [comment]
What are you looking to accomplish? I can probably help you better if I know what you're aiming for.

**Comment by rhizoome** [comment]
> thx a lot for the hint @SamiPerttu , I will give it a try and come back to this thread

Put whatever you build in a net then signature becomes `Box<dyn AudioUnit>`

fn build_bank_simd() -> Box<dyn AudioUnit> {
    Box::new(Net::wrap(Box::new(
        noise() >> split() >> res_bank(440.0) >> join() * 0.1,
    )))
}

Also use [embassy](https://embassy.dev) or at least [rtic](https://rtic.rs/2/book/en/) and you don't need static variables.

**Comment by nwesem** [comment]
I will try it with embassy but my chip is currently not fully supported so this will take some time until I can send the solution. Thx a lot for the hint @rhizoome I will get embassy working first and then revisit this thread @SamiPerttu also thx to you

**Comment by nwesem** [comment]
Thanks @rhizoome it is actually supported with embassy via https://github.com/Dicklessgreat/daisy_embassy
