### ISSUE TITLE
the beep example is not working for windows 10

### ISSUE THREAD

**Issue by chaosprint** [SamiPerttu/fundsp#5]
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 8.90 GB / 15.93 GB
```
compile is successful, but the audio is completely distorted

**Comment by SamiPerttu** [comment]
The debug mode distorts because it's too slow to process audio. Try running in release mode, that should work without issues.

**Comment by RobDavenport** [comment]
Was also having this issue but was fixed by running in release mode. I'm not too familiar with audio at all, but is this a common problem (debug not being able to process audio)?

**Comment by SamiPerttu** [comment]
It means the compiler does a lot of heavy lifting to optimize code in release mode. This situation is not uncommon in Rust. The biggest culprit appears to be the reverb effect, which is especially slow in debug mode.
