### ISSUE TITLE
Sequence backend does not have the capacity and allocates when an event is scheduled in it

### ISSUE THREAD

**Issue by Sorseg** [SamiPerttu/fundsp#54]
The containers for the sequencer have some pre-allocated capacity, which is lost when the containers are cloned for the backend here
https://github.com/SamiPerttu/fundsp/blob/0df9e07237c7c05523b7a52c911e9d1b81c3999d/src/sequencer.rs#L536

Experiment
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8bc4f9915bef65696a4f8018daed9812

The `allocate` call also does not allocate the buffers for the sequencer

**Comment by Sorseg** [comment]
I'll try to whip up a PR that fixes that

**Comment by SamiPerttu** [comment]
Yikes! Thanks for the fix.
