### ISSUE TITLE
How to have a variable delay ?

### ISSUE THREAD

**Issue by DimitriTimoz** [SamiPerttu/fundsp#56]
Is it possible with the implemented filters to have a variable delay according the time. I mean with a Shared variable when a value is set the sound will take this value be transmited.

**Comment by SamiPerttu** [comment]
Hi! Yes, the `tap` opcode does cubic interpolation, while `tap_linear` does linear interpolation. For example:
```rust
use fundsp::hacker::*;
let min_delay = 0.1;
let max_delay = 2.0;
let delay_time = shared(1.0);
let delay = (pass() | var(&delay_time)) >> tap(min_delay, max_delay);
```
If you change the delay suddenly, you're going to hear clicks. It's possible to smooth the transitions but then you get Doppler effects. If you want discrete changes then it would be best to crossfade between delays. There's no component for that at the moment but I'm putting it on the TODO list. The smoothed version would be (here with a smoothing timescale of 0.1 seconds):
```rust
let delay = (pass() | var(&delay_time) >> follow(0.1)) >> tap(min_delay, max_delay);
```

**Comment by DimitriTimoz** [comment]
> Hi! Yes, the `tap` opcode does cubic interpolation, while `tap_linear` does linear interpolation. For example:
> 
> ```rust
> use fundsp::hacker::*;
> let min_delay = 0.1;
> let max_delay = 2.0;
> let delay_time = shared(1.0);
> let delay = (pass() | var(&delay_time)) >> tap(min_delay, max_delay);
> ```
> 
> If you change the delay suddenly, you're going to hear clicks. It's possible to smooth the transitions but then you get Doppler effects. If you want discrete changes then it would be best to crossfade between delays. There's no component for that at the moment but I'm putting it on the TODO list. The smoothed version would be (here with a smoothing timescale of 0.1 seconds):
> 
> ```rust
> let delay = (pass() | var(&delay_time) >> follow(0.1)) >> tap(min_delay, max_delay);
> ```

Ok, thank you.
Indeed, I need a discrete change. 
I'm discovering your crate for creating an immersive voice chat system. You did a really good job.
