### ISSUE TITLE
Stream mono -> process -> Stereo

### ISSUE THREAD

**Issue by DimitriTimoz** [SamiPerttu/fundsp#57]
I don't understand well how to extract the samples of the `Net`.
My `Net` has a stream as `An(InputNode)` as input, I split the mono channel to stereo channel but to get the setreo sample it's not possible. 
Indeed, `backend.get_stereo()` allow only mono channel in input.
Do I have to write my Unit to process my stream input with `backend.process(..)` ?
To sum up, here is what I want:

```rust
  let input = InputNode::new(receiver);

  let (left_amp, right_amp) = (shared(1.0), shared(1.0));

  let mut net = Net::wrap(Box::new(An(input)));

  net.set_sample_rate(sample_rate);

  // Stereo effects
  let output_node = net.chain(Box::new(
      (pass() * var(&left_amp)) ^ (pass() * var(&right_amp)),
  ));
  println!(
      "Output node: {:?}",
      (sine() >> (pass() * var(&left_amp)) ^ (pass() * var(&right_amp))).outputs()
  );
  net.check();

let mut backend = net.backend();
let mut next_value = move || assert_no_alloc(|| backend.get_stereo()); // Here get the 2 differents channels and not duplicate stereo

```

**Comment by SamiPerttu** [comment]
Hi! `get_stereo` expects the `Net` to have no inputs. If you have an input then where is the data coming from? In any case, you can use the `tick` method for processing single samples. The following works for 1 input and 2 outputs.
```rust
let input = [0.0];
let mut output = [0.0, 0.0];
net.tick(&input, &mut output);
// Now output contains the two output samples.
```

**Comment by DimitriTimoz** [comment]
Thank you for the clarification.
