### ISSUE TITLE
Excessive Memory usage in FFT conversion

### ISSUE THREAD

**Issue by orukusaki** [SamiPerttu/fundsp#60]
Hi,
I'm using fundsp on arm cortex-m4 and m7 chips, via https://github.com/orukusaki/owl_patch
I created a test patch using the example from the resynth docs:
```rust
    let mut unit = resynth::<U1, U1, _>(32, |fft| {
        for i in 0..fft.bins() {
            if fft.frequency(i) <= cutoff.value() {
                fft.set(0, i, fft.at(0, i));
            }
        }
    });
```
But found I was running out of stack memory.

Inspecting the assembly output I see this line:
```
24001b06:	f5ad 2d00 	sub.w	sp, sp, #524288	@ 0x80000
```
That's 524288 bytes of stack memory being reserved. Might not be a lot for a PC, but for a microcontroller it is too much.

The culprits seem to be `fundsp::fft::real_fft` and `fundsp::fft::inverse_fft`. Both of these functions use a `match` to transform a slice to a fixed length array:
```rust   
    match input.len() {
        2 => {
            let mut tmp: [f32; 2] = from_fn(|i| input[i]);
            output[..1].copy_from_slice(rfft_2(&mut tmp));
        }
        4 => {
            let mut tmp: [f32; 4] = from_fn(|i| input[i]);
            output[..2].copy_from_slice(rfft_4(&mut tmp));
        }
// etc
        32768 => {
            let mut tmp: [f32; 32768] = from_fn(|i| input[i]);
            output[..16384].copy_from_slice(rfft_32768(&mut tmp));
        }
```
~~However because it can't know at compile time what size buffer will be needed, the compiler allows enough memory for all of these buffers at once.  That's 65534 * 4 * 2 = 524272 bytes!~~

~~I'm not sure what the best solution is, but currently these functions are using double what should be their worst-case memory usage.~~

Ok that wasn't quite correct - the compiler only allocates the maximum buffer size, the rest of the usage must come from the microfft functions.  Still, it would be good if there was a way to only allocate what is needed - even if it's on the heap

**Comment by SamiPerttu** [comment]
Hi! It should be fixed now. I removed stack allocations and optimized memory usage in `resynth`.

**Comment by orukusaki** [comment]
Thanks! I was trying to test this this morning, but it seems like there's something else wrong, I can't get even a simple example to run now on the latest fundsp commit. I've checked back and the latest version that works for me is 84ed485. 3017484 doesn't compile, 05b3efd and later compiles but doesn't run.  

I'll investigate more later, but I suspect it's got something to do with the maths changes - the newer versions seem to assume I have `f64::tan()` (etc) available from std, which I do not. Previously the `libm` version would have been used via the `Real` impl.

**Comment by SamiPerttu** [comment]
Thanks for checking, I'm going to look at this as well.

**Comment by orukusaki** [comment]
Cool the latest version works for me, and the memory issue is fixed too. Thanks for sorting this :)
