### ISSUE TITLE
Sequencer is CPU-hungry

### ISSUE THREAD

**Issue by jangler** [SamiPerttu/fundsp#62]
I'm noticing that fundsp uses much more processor time (maybe ~5× as much?) if I'm working through a Sequencer. It also seems like the number of active Events is the main factor that determines how much CPU is used rather than the total amount of DSP going on inside the events. (This was all measured from release mode builds.) Is there a fix for this or should I avoid Sequencer if there might be a lot of concurrent voices?

**Comment by dathinaios** [comment]
The number of active events will be the main factor as every event concurrently active will double the resources used. Do you mean that if you activate the same number of events using something other than 'sequencer' you are getting a different result?

**Comment by jangler** [comment]
I'm sorry, I was completely off track here! The component hogging CPU in my use case wasn't even part of fundsp, and the association with `Sequencer` was a coincidence.
