### ISSUE TITLE
Wavetable oscillators increase in amplitude as pitch increases

### ISSUE THREAD

**Issue by jangler** [SamiPerttu/fundsp#63]
If I record the output of `envelope(|t| 55.0 * pow(2.0, t)) >> triangle()`, it looks like this:

![image](https://github.com/user-attachments/assets/f156b2e4-ad63-440d-8bf9-dc706a000957)

`pulse` and `saw` also have this issue. I haven't tested the other wavetable oscillators. `sine` works as expected. I'm using v0.20.0.

**Comment by SamiPerttu** [comment]
Hi! It should be fixed now.

**Comment by jangler** [comment]
Thanks, looks good now!
