### ISSUE TITLE
Provide `hacker` in 32-bit "mode"

### ISSUE THREAD

**Issue by Emilgardis** [SamiPerttu/fundsp#7]
Would it be possible to expose another `hacker` module but for 32-bit mode? Potentially a `hacker32` module behind a feature flag.

I tried doing this myself, but I'm not very successful as some items make assumptions about the sample size/type and wrongly(?) sets some type bounds, making it hard to progress without good knowledge of how everything fits together.

**Comment by Emilgardis** [comment]
One example of this is `Limiter`, where the sample needs to be `f64`
https://github.com/SamiPerttu/fundsp/blob/1dea143f68493f97be4e9ff488aa1d3e23ea75bb/src/dynamics.rs#L161-L166

**Comment by Emilgardis** [comment]
Can make a pr if this is something that is wanted, I think this works!

https://github.com/Emilgardis/fundsp/commit/1a831b41757101e16e3c34f4ef49a8db551c9e39

**Comment by SamiPerttu** [comment]
The `limiter` thingy looks like a bug, I'll look into it. I agree with your request in that it would make sense to have 64-bit and 32-bit preludes and discard the generic prelude. If you want to make a PR, that would be fine. Otherwise I'll look into it.
