### ISSUE TITLE
option to increase buffer size

### ISSUE THREAD

**Issue by Emilgardis** [SamiPerttu/fundsp#8]
Is there a reason for having the max buffer size set at 64?

My use case is using block processing to interface with a live input/output with >64 samples (128 to 2048) per "frame".

A buffer of 64 items is not enough for this.

**Comment by SamiPerttu** [comment]
I think the stated reason is to make it easier to stack allocate buffers. Which is not taken advantage of right now. I'm not sure what is the best way forward, do we need the limit or not.
